{
  "openapi": "3.0.1",
  "info": {
    "version": "2.0.2",
    "title": "Swagger Drinkmaster",
    "description": "Showing off swagger-ui-express",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [
    { "url": "http://localhost:3000" },
    { "url": "https://drink-master-app.onrender.com" }
  ],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "Users",
      "description": "Users endpoints"
    },
    {
      "name": "Filters",
      "description": "Filter endpoints"
    },
    {
      "name": "Drinks",
      "description": "Drink endpoints"
    }
  ],
  "paths": {
    "/api/auth/signup": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Email already exist.",
            "content": {}
          }
        }
      }
    },
    "/api/auth/signin": {
      "post": {
        "tags": ["Auth"],
        "summary": "User authorisation",
        "parameters": [],
        "requestBody": {
          "description": "Authorisation's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AuthorisationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthorisationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          }
        }
      }
    },
    "/api/auth/signout": {
      "post": {
        "tags": ["Auth"],
        "summary": "User logout",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Logout",
          "required": false,
          "content": []
        },
        "responses": {
          "204": {
            "description": "No content"
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          }
        }
      }
    },
    "/api/users/current": {
      "post": {
        "tags": ["Users"],
        "summary": "User information",
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "requestBody": [],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          }
        }
      }
    },
    "/api/users/update": {
      "patch": {
        "tags": ["Users"],
        "summary": "User update",
        "consumes": ["multipart/form-data"],
        "security": [{ "Bearer": [] }],
        "parameters": [],
        "requestBody": {
          "description": "Update object",
          "required": true,
          "content": {
            " multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateUserRespons"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {}
          }
        }
      }
    },
    "/api/filters/categories": {
      "get": {
        "tags": ["Filters"],
        "summary": "Categories list",
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Categories list",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CategoriesResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/api/filters/ingredients": {
      "get": {
        "tags": ["Filters"],
        "summary": "Ingredients list",
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Ingredients list",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IngredientsResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/api/filters/glasses": {
      "get": {
        "tags": ["Filters"],
        "summary": "Glasses list",
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Glasses list",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GlassesResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/api/drinks/mainpage": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Gets drinks sorted by categories",
        "security": [{ "Bearer": [] }],
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MainpageResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/api/drinks/popular": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Gets popular drinks",
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PopularDrinksResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not found"
          }
        }
      },
      "/api/drinks/own/add": {
        "post": {
          "tags": ["Drinks"],
          "summary": "Add user's recipe of drink",
          "security": [{ "Bearer": [] }],
          "requestBody": {
            "description": "User's recipe object",
            "required": true,
            "content": {
              "multipart/form-data": {
                "schema": {
                  "$ref": "#/components/schemas/AddOwnDrinkRequest"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Drink successfully added",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/AddOwnDrinkResponse"
                  }
                }
              }
            },
            "401": {
              "description": "Unauthorized"
            },
            "404": {
              "description": "Not found"
            }
          }
        }
      },
      "/api/drinks/own": {
        "get": {
          "tags": ["Drinks"],
          "summary": "Get user's own drinks",
          "security": [{ "Bearer": [] }],
          "parameters": [
            {
              "in": "query",
              "name": "page",
              "description": "Number of page. Default page = 1"
            },
            {
              "in": "query",
              "name": "limit",
              "description": "Number of drinks on one page. Default limit = 10"
            }
          ],
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/AllOwnDrinksResponse"
                  }
                }
              }
            },
            "401": {
              "description": "Unauthorized"
            }
          }
        }
      },
      "/api/drinks/own/remove/{id}": {
        "delete": {
          "tags": ["Drinks"],
          "summary": "Delete user's own drink",
          "parameters": [
            {
              "in": "path",
              "name": "id",
              "required": true,
              "description": "Drink id"
            }
          ],
          "security": [{ "Bearer": [] }],
          "responses": {
            "200": {
              "description": "Drink successfully removed"
            },
            "403": {
              "description": "User is not authorized to delete this drink"
            },
            "404": {
              "description": "Not found"
            }
          }
        }
      },
      "/api/drinks/favorite": {
        "get": {
          "tags": ["Drinks"],
          "summary": "Get drinks from favorites",
          "parameters": [
            {
              "in": "query",
              "name": "page",
              "description": "Number of page. Default page = 1"
            },
            {
              "in": "query",
              "name": "limit",
              "description": "Number of cocktails on one page. Default limit = 10"
            }
          ],
          "security": [{ "Bearer": [] }],
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/AllFavoritesResponse"
                  }
                }
              }
            },
            "401": {
              "description": "Unauthorized"
            },
            "404": {
              "description": "Not found"
            }
          }
        }
      },"/api/drinks/favorite/add/{id}": {
        "post": {
          "tags": ["Drinks"],
          "summary": "Add drink to favorites",
          "parameters": [
            {
              "in": "path",
              "name": "id",
              "required": true,
              "schema": {
                "type": "string",
                "format": "objectId",
                "description": "Drink id"
              },
              "description": "Drink id"
            }
          ],
          "security": [{ "Bearer": [] }],
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/AddToFavoritesResponse"
                  }
                }
              }
            },
            "401": {
              "description": "Unauthorized"
            },
            "404": {
              "description": "Not found"
            }
          }
        }
      },"/api/drinks/favorite/remove/{id}": {
        "delete": {
          "tags": ["Drinks"],
          "summary": "Remove drink from favorites",
          "parameters": [
            {
              "in": "path",
              "name": "id",
              "required": true,
              "schema": {
                "type": "string",
                "format": "objectId",
                "description": "Drink id"
              },
              "description": "Drink id"
            }
          ],
          "security": [{ "Bearer": [] }],
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/DeleteFromFavoritesResponse"
                  }
                }
              }
            },
            "401": {
              "description": "Unauthorized"
            },
            "404": {
              "description": "Not found"
            }
          }
        }
      }
    },
    "/api/drinks/search": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Search Drinks",
        "security": [{ "Bearer": [] }],
        "description": "Enables drink search based on a variety of criteria",
        "parameters": [
          {
            "name": "ingredient",
            "in": "query",
            "description": "Title of ingridient, that used in the drink",
            "required": false,
            "type": "string"
          },
          {
            "name": "drink",
            "in": "query",
            "description": "Query for drink names in the search",
            "required": false,
            "type": "string"
          },
          {
            "name": "category",
            "in": "query",
            "description": "Drink category",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "Ordinary Drink",
                "Cocktail",
                "Shake",
                "Other/Unknown",
                "Cocoa",
                "Shot",
                "Coffee / Tea",
                "Homemade Liqueur",
                "Punch / Party Drink",
                "Beer",
                "Soft Drink"
              ]
            }
          },
          {
            "name": "page",
            "in": "query",
            "description": "Page number of results",
            "required": false,
            "type": "integer"
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Number of results per page",
            "required": false,
            "type": "integer"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SearchDrinksResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/api/drinks/{id}": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Get drink by id",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string",
              "format": "objectId",
              "description": "Drink id"
            },
            "description": "Drink id"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DrinkByIdResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    }, "/api/drinks/own/add": {
      "post": {
        "tags": ["Drinks"],
        "summary": "Add user's recipe of drink",
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "User's recipe object",
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/AddOwnDrinkRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Drink successfully added",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddOwnDrinkResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/api/drinks/own": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Get user's own drinks",
        "security": [{ "Bearer": [] }],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "description": "Number of page. Default page = 1"
          },
          {
            "in": "query",
            "name": "limit",
            "description": "Number of drinks on one page. Default limit = 10"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AllOwnDrinksResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/api/drinks/own/remove/{id}": {
      "delete": {
        "tags": ["Drinks"],
        "summary": "Delete user's own drink",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "description": "Drink id"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Drink successfully removed"
          },
          "403": {
            "description": "User is not authorized to delete this drink"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/api/drinks/favorite": {
      "get": {
        "tags": ["Drinks"],
        "summary": "Get drinks from favorites",
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "description": "Number of page. Default page = 1"
          },
          {
            "in": "query",
            "name": "limit",
            "description": "Number of cocktails on one page. Default limit = 10"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AllFavoritesResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },"/api/drinks/favorite/add/{id}": {
      "post": {
        "tags": ["Drinks"],
        "summary": "Add drink to favorites",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string",
              "format": "objectId",
              "description": "Drink id"
            },
            "description": "Drink id"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddToFavoritesResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },"/api/drinks/favorite/remove/{id}": {
      "delete": {
        "tags": ["Drinks"],
        "summary": "Remove drink from favorites",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string",
              "format": "objectId",
              "description": "Drink id"
            },
            "description": "Drink id"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteFromFavoritesResponse"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    }
  },

  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["name", "email", "password", "birthDate"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Test"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "test@example.com"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          },
          "birthDate": {
            "type": "string",
            "description": "User's birthDate",
            "example": "20 Aug 2000"
          }
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Test"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "test@example.com"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          },
          "birthDate": {
            "type": "string",
            "description": "User's birthDate",
            "example": "20 Aug 2000"
          },
          "userId": {
            "type": "number",
            "description": "User's id",
            "example": "32143232436545474"
          },
          "isAdult": {
            "type": "boolein",
            "description": "",
            "example": "true"
          },
          "subscribe": {
            "type": "boolein",
            "description": "subscribe",
            "example": "true"
          },
          "avatar": {
            "type": "string",
            "description": "avatar",
            "example": "https//www.gravatar.com/avatar"
          },
          "refreshToken": {
            "type": "string",
            "description": "User's refreshToken",
            "example": "d113fc3f8c70bc958ff763c03bcc5ebbc563bb313386f922da4a891bf3049624"
          }
        },
        "example": {
          "name": "example",
          "email": "1example@gmail.com",
          "birthDate": "20 Aug 2010",
          "isAdult": "true",
          "subscribe": "true",
          "userId": "1573839013698358109",
          "avatar": "https//www.gravatar.com/avatar",
          "refreshToken": "d113fc3f8c70bc958ff763c03bcc5ebbc563bb313386f922da4a891bf3049624"
        }
      },
      "AuthorisationRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "test@example.com"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "AuthorisationResponse": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "test@example.com"
          },
          "token": {
            "type": "string",
            "description": "User's token",
            "example": "d113fc3f8c70bc958ff763c03bcc5ebbc563bb313386f922da4a891bf3049624"
          }
        },
        "example": {
          "email": "1example@gmail.com",
          "token": "d113fc3f8c70bc958ff763c03bcc5ebbc563bb313386f922da4a891bf3049624"
        }
      },
      "CurrentResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Test"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "test@example.com"
          },
          "birthDate": {
            "type": "string",
            "description": "User's birthDate",
            "example": "20 Aug 2020"
          }
        },
        "example": {
          "name": "Test",
          "email": "1example@gmail.com",
          "birthDate": "20 Aug 2020"
        }
      },
      "UpdateUserRequest": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Test"
          },
          "avatar": {
            "type": "string",
            "description": "User's avatar",
            "format": "binary",
            "example": "https://res.cloudinary.com/dzvvgvwgt/image/upload/v1699195131/drinkMaster/avatar/65456b585b4eb0cd117b6a6c.jpg"
          }
        }
      },
      "UpdateUserRespons": {},
      "CategoriesResponse": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "example": ["Beer", "Shot", "Shake"]
      }, "IngredientsResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string",
              "description": "Ingredient id"
            },
            "title": {
              "type": "string",
              "description": "Ingredient title"
            },
            "ingredientThumb": {
              "type": "string",
              "format": "uri",
              "description": "URL to ingredient image"
            },
            "thumb-medium": {
              "type": "string",
              "format": "uri",
              "description": "Ingredient medium image URL"
            },
            "thumb-small": {
              "type": "string",
              "format": "uri",
              "description": "URL to ingredient small image"
            },
            "abv": {
              "type": "string",
              "description": "Ingredient's abv"
            },
            "alcocol": {
              "type": "string",
              "description": "Ingredient's alcohol"
            },
            "description": {
              "type": "string",
              "description": "Ingredient's description"
            },
            "type": {
              "type": "string",
              "description": "Ingredient's type"
            },
            "flavour": {
              "type": "string",
              "description": "Ingredient's flavour"
            },
            "country": {
              "type": "string",
              "description": "Ingredient's origin country"
            }
          }
        },
        "example": [
          {
        "_id": "64aebb7f82d96cc69e0eb4b3",
        "title": "Amaretto",
        "ingredientThumb": "https://ftp.goit.study/img/drinkify/ingredients/Amaretto.png",
        "thumb-medium": "https://ftp.goit.study/img/drinkify/ingredients/Amaretto-Medium.png",
        "thumb-small": "https://ftp.goit.study/img/drinkify/ingredients/Amaretto-Small.png",
        "abv": "28",
        "alcohol": "Yes",
        "description": "Amaretto (Italian for \"a little bitter\") is a sweet, almond-flavoured, Italian liqueur associated with Saronno, Italy. Various commercial brands are made from a base of apricot pits, almonds, or both.\r\n\r\nWhen served as a beverage, amaretto can be drunk by itself, used as an ingredient to create several popular mixed drinks, or added to coffee. Amaretto is also commonly used in culinary applications.\r\n\r\nThe name amaretto originated as a diminutive of the Italian word amaro, meaning \"bitter\", which references the distinctive flavour lent by the mandorla amara (the bitter almond) or by the drupe kernel. However, the bitterness of amaretto tends to be mild, and sweeteners—and sometimes sweet almonds—enhance the flavour in the final products. Thus one can interpret the liqueur's name as a description of the taste as \"a little bitter\". Cyanide is processed out of the almond preparation prior to its use.\r\n\r\nConflation of amaro (\"bitter\") and amore (\"love\") has led to associations with romance.\r\n\r\nOne should not confuse amaretto with amaro, a different family of Italian liqueurs that, while also sweetened, have a stronger bitter flavour derived from herbs.",
        "type": "Liqueur",
        "flavour": "almond",
        "country": "Italy"
          }
        ]
      },
      "GlassesResponse": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "example": ["Coffee mug", "Cocktail glass", "Cordial glass"]
      },
      "MainpageResponse": {
        "type": "object",
        "properties": {
          "Ordinary Drink": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string"
                },
                "drink": {
                  "type": "string"
                },
                "drinkAlternate": {
                  "type": "string"
                },
                "tags": {
                  "type": "string"
                },
                "video": {
                  "type": "string"
                },
                "category": {
                  "type": "string"
                },
                "IBA": {
                  "type": "string"
                },
                "alcoholic": {
                  "type": "string"
                },
                "glass": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "instructions": {
                  "type": "string"
                },
                "instructionsES": {
                  "type": "string"
                },
                "instructionsDE": {
                  "type": "string"
                },
                "instructionsFR": {
                  "type": "string"
                },
                "instructionsIT": {
                  "type": "string"
                },
                "instructionsRU": {
                  "type": "string"
                },
                "instructionsPL": {
                  "type": "string"
                },
                "instructionsUK": {
                  "type": "string"
                },
                "drinkThumb": {
                  "type": "string"
                },
                "ingredients": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": {
                        "type": "string"
                      },
                      "title": {
                        "type": "string"
                      },
                      "measure": {
                        "type": "string"
                      },
                      "ingredientId": {
                        "type": "string"
                      }
                    }
                  }
                },
                "shortDescription": {
                  "type": "string"
                },
                "updatedAt": {
                  "type": "string"
                },
                "users": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "example": {
          "Ordinary Drink": [
            {
              "_id": "639b6de9ff77d221f190c56d",
              "drink": "Daiquiri",
              "drinkAlternate": "Sorry, not specified",
              "tags": "IBA,Classic,Beach",
              "video": "Sorry, not specified",
              "category": "Ordinary Drink",
              "IBA": "Sorry, not specified",
              "alcoholic": "Alcoholic",
              "glass": "Cocktail glass",
              "description": "Daiquiri is a classic and refreshing cocktail that has stood the test of time. It is made with rum, lime juice, and simple syrup. The combination of tart lime juice, smooth rum, and a touch of sweetness creates a well-balanced and delightful drink. Whether you prefer it shaken or frozen, the Daiquiri is a versatile and timeless choice for any occasion.",
              "instructions": "Pour all ingredients into shaker with ice cubes. Shake well. Strain in chilled cocktail glass.",
              "instructionsES": "Vierta todos los ingredientes en la coctelera con cubitos de hielo. Agite bien. Colar en copa de cóctel fría.",
              "instructionsDE": "Alle Zutaten in den Shaker mit Eiswürfel geben. Gut schütteln. In einem gekühlten Cocktailglas abseihen.",
              "instructionsFR": "Verser tous les ingrédients dans un shaker avec des glaçons. Bien agiter. Filtrer dans un verre à cocktail refroidi.",
              "instructionsIT": "Versare tutti gli ingredienti nello shaker con cubetti di ghiaccio.Filtrare in una coppetta da cocktail ghiacciata. Agitare bene",
              "instructionsRU": "Налейте все ингредиенты в шейкер с кубиками льда. Хорошо встряхнуть. Процедить в охлажденный коктейльный бокал.",
              "instructionsPL": "Wszystkie składniki wlej do shakera z kostkami lodu. Dobrze wstrząsnąć. Odcedź w schłodzonym kieliszku koktajlowym.",
              "instructionsUK": "Перелийте всі інгредієнти в шейкер з кубиками льоду. Добре струсити. Процідити в охолоджений коктейльний келих.",
              "drinkThumb": "https://ftp.goit.study/img/drinkify/recipes/Daiquiri.jpg",
              "ingredients": [
                  {
                      "_id": "65493f119ee3f7ef42ffc488",
                      "title": "Light rum",
                      "measure": "1 1/2 oz ",
                      "ingredientId": "64aebb7f82d96cc69e0eb4a4"
                  },
                  {
                      "_id": "65493f119ee3f7ef42ffc489",
                      "title": "Lime",
                      "measure": "Juice of 1/2 ",
                      "ingredientId": "64aebb7f82d96cc69e0eb4db"
                  },
                  {
                      "_id": "65493f119ee3f7ef42ffc48a",
                      "title": "Powdered sugar",
                      "measure": "1 tsp ",
                      "ingredientId": "64f1d5c369d8333cf130fb78"
                  }
              ],
              "shortDescription": "A classic and refreshing cocktail with rum, lime juice, and simple syrup.",
              "updatedAt": "2023-11-06T19:14:04.870Z",
              "users": [
                  "6548f92d7344e11d1d129d8a",
                  "6548e4b97344e11d1d1181ea"
              ]
          }
          ]
        }
      },
      "PopularDrinksResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "drink": {
              "type": "string"
            },
            "drinkAlternate": {
              "type": "string"
            },
            "tags": {
              "type": "string"
            },
            "video": {
              "type": "string"
            },
            "category": {
              "type": "string"
            },
            "IBA": {
              "type": "string"
            },
            "alcoholic": {
              "type": "string"
            },
            "glass": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "instructions": {
              "type": "string"
            },
            "instructionsES": {
              "type": "string"
            },
            "instructionsDE": {
              "type": "string"
            },
            "instructionsFR": {
              "type": "string"
            },
            "instructionsIT": {
              "type": "string"
            },
            "instructionsRU": {
              "type": "string"
            },
            "instructionsPL": {
              "type": "string"
            },
            "instructionsUK": {
              "type": "string"
            },
            "drinkThumb": {
              "type": "string"
            },
            "ingredients": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "measure": {
                    "type": "string"
                  },
                  "ingredientId": {
                    "type": "string"
                  }
                }
              }
            },
            "shortDescription": {
              "type": "string"
            },
            "updatedAt": {
              "type": "string"
            },
            "users": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "example": [
          {
        "_id": "639b6de9ff77d221f190c50f",
        "drink": "Quentin",
        "drinkAlternate": "Sorry, not specified",
        "tags": "IBA,ContemporaryClassic",
        "video": "https://www.youtube.com/watch?v=2jtoa_t7g94",
        "category": "Ordinary Drink",
        "IBA": "Contemporary Classics",
        "alcoholic": "Alcoholic",
        "glass": "Cocktail glass",
        "description": "Quentin is a refreshing cocktail that combines the flavors of citrus and mint. It is made with fresh lime juice, orange liqueur, and a touch of mint syrup. The drink is served over ice and garnished with a sprig of mint. It is the perfect beverage for a hot summer day.",
        "instructions": "In a shaker half-filled with ice cubes, combine the rum, Kahlua, and cream. Shake well. Strain into a cocktail glass and garnish with the nutmeg.",
        "instructionsES": "En una coctelera llena hasta la mitad con cubitos de hielo, combine el ron, Kahlua y la crema. Agite bien. Colar en una copa de cóctel y decorar con la nuez moscada.",
        "instructionsDE": "In einem Shaker, der halb mit Eiswürfeln gefüllt ist, Rum, Kahlua und Sahne mischen. Gut schütteln. In ein Cocktailglas abseihen und mit der Muskatnuss garnieren.",
        "instructionsFR": "Dans un shaker à moitié rempli de glaçons, mélanger le rhum, le Kahlua et la crème. Bien agiter. Versez dans un verre à cocktail et décorez avec la noix de muscade.",
        "instructionsIT": "In uno shaker riempito a metà con cubetti di ghiaccio, unire il rum, il Kahlua e la panna. Filtrare in una coppetta da cocktail e guarnire con la noce moscata. Agitare bene.",
        "instructionsRU": "В шейкере, наполовину наполненном кубиками льда, смешайте ром, Калуа и сливки. Хорошо встряхнуть. Процедите в коктейльный бокал и украсьте мускатным орехом.",
        "instructionsPL": "W shakerze wypełnionym do połowy kostkami lodu wymieszać rum, Kahlua i śmietanę. Dobrze wstrząsnąć. Przelej do kieliszka koktajlowego i udekoruj gałką muszkatołową.",
        "instructionsUK": "У шейкері, наповненому наполовину кубиками льоду, змішайте ром, Калуа та вершки. Добре струсити. Процідіть у келих для коктейлю та прикрасьте мускатним горіхом.",
        "drinkThumb": "https://ftp.goit.study/img/drinkify/recipes/Quentin.jpg",
        "ingredients": [
            {
                "title": "Dark rum",
                "measure": "1 1/2 oz ",
                "ingredientId": "64aebb7f82d96cc69e0eb4a7"
            },
            {
                "title": "Kahlua",
                "measure": "1/2 oz ",
                "ingredientId": "64aebb7f82d96cc69e0eb4bd"
            },
            {
                "title": "Light cream",
                "measure": "1 oz ",
                "ingredientId": "64f1d5c069d8333cf130fb31"
            },
            {
                "title": "Nutmeg",
                "measure": "1/8 tsp grated ",
                "ingredientId": "64f1d5c069d8333cf130fb34"
            }
        ],
        "shortDescription": "A refreshing and citrusy cocktail with a hint of mint.",
        "updatedAt": "2023-11-03T20:57:13.653Z",
        "users": [
            "653e747a0d2bb3830f82eb47",
            "6543e1144b22e0e1b4948877",
            "6540c1977366a77795807a1a"
        ],
        "popularity": 3
    }
        ]
      },
      "SearchDrinksResponse": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "description": "Response code"
          },
          "message": {
            "type": "string",
            "description": "Response message"
          },
          "quantityTotal": {
            "type": "integer",
            "description": "Total number of drinks found"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string",
                  "description": "Drink ID"
                },
                "drink": {
                  "type": "string",
                  "description": "Name of the drink"
                },
                "category": {
                  "type": "string",
                  "description": "Category of the drink"
                },
                "alcoholic": {
                  "type": "string",
                  "description": "Alcoholic content of the drink"
                },
                "drinkThumb": {
                  "type": "string",
                  "description": "URL of the drink's image"
                } 
              }
            }
          }
        },
        "example": {
          "code": 200,
          "message": "Success operation",
          "quantityTotal": 1,
          "data": [
              {
                  "_id": "639b6de9ff77d221f190c55a",
                  "drink": "Jam Donut",
                  "category": "Shot",
                  "alcoholic": "Alcoholic",
                  "drinkThumb": "https://ftp.goit.study/img/drinkify/recipes/Jam_Donut.jpg"
              }
          ]
      }
      },
      "DrinkByIdResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "description": "Drink ID"
          },
          "drink": {
            "type": "string",
            "description": "Name of the drink"
          },
          "drinkAlternate": {
            "type": "string",
            "description": "Alternate name for the drink"
          },
          "tags": {
            "type": "string",
            "description": "Tags for the drink"
          },
          "video": {
            "type": "string",
            "description": "URL of the drink's video"
          },
          "category": {
            "type": "string",
            "description": "Category of the drink"
          },
          "IBA": {
            "type": "string",
            "description": "International Bartenders Association (IBA) category"
          },
          "alcoholic": {
            "type": "string",
            "description": "Alcoholic volume of the drink"
          },
          "glass": {
            "type": "string",
            "description": "Type of glass for the drink"
          },
          "description": {
            "type": "string",
            "description": "Description of the drink"
          },
          "instructions": {
            "type": "string",
            "description": "Instructions for making the drink (in English)"
          },
          "instructionsES": {
            "type": "string",
            "description": "Instructions for making the drink (in Spanish)"
          },
          "instructionsDE": {
            "type": "string",
            "description": "Instructions for making the drink (in German)"
          },
          "instructionsFR": {
            "type": "string",
            "description": "Instructions for making the drink (in French)"
          },
          "instructionsIT": {
            "type": "string",
            "description": "Instructions for making the drink (in Italian)"
          },
          "instructionsRU": {
            "type": "string",
            "description": "Instructions for making the drink (in Russian)"
          },
          "instructionsPL": {
            "type": "string",
            "description": "Instructions for making the drink (in Polish)"
          },
          "instructionsUK": {
            "type": "string",
            "description": "Instructions for making the drink (in Ukrainian)"
          },
          "drinkThumb": {
            "type": "string",
            "description": "URL of the drink's image"
          },
          "ingredients": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string",
                  "description": "Unique identifier for the ingredient"
                },
                "title": {
                  "type": "string",
                  "description": "Name of the ingredient"
                },
                "measure": {
                  "type": "string",
                  "description": "Measurement quantity of the ingredient"
                },
                "ingredientId": {
                  "type": "string",
                  "description": "Unique identifier for the ingredient in the database"
                }
              }
            }
          },
          "shortDescription": {
            "type": "string",
            "description": "Short drink description"
          }
        },
        "example": {
          "users": [],
          "_id": "639b6de9ff77d221f190c502",
          "drink": "Yellow Bird",
          "drinkAlternate": "Sorry, not specified",
          "tags": "IBA,NewEra",
          "video": "Sorry, not specified",
          "category": "Cocktail",
          "IBA": "New Era Drinks",
          "alcoholic": "Alcoholic",
          "glass": "Cocktail glass",
          "description": "Yellow Bird is a tropical and fruity cocktail that captures the essence of a sunny paradise. It features the flavors of rum, Galliano liqueur, lime juice, and pineapple juice. This vibrant and refreshing drink is perfect for sipping by the pool or enjoying on a beach vacation. Treat yourself to a Yellow Bird and let its tropical flavors transport you to an island getaway.",
          "instructions": "Shake and strain into a chilled cocktail glass",
          "instructionsES": "Agitar y colar en una copa de cóctel fría",
          "instructionsDE": "In ein gekühltes Cocktailglas schütteln und abseihen.",
          "instructionsFR": "Secouer et filtrer dans un verre à cocktail refroidi",
          "instructionsIT": "Shakerare e filtrare in una coppetta da cocktail ghiacciata",
          "instructionsRU": "Встряхнуть и процедить в охлажденный коктейльный бокал",
          "instructionsPL": "Wstrząśnij i przelej do schłodzonego kieliszka koktajlowego",
          "instructionsUK": "Струсіть і процідіть у охолоджений келих для коктейлю",
          "drinkThumb": "https://ftp.goit.study/img/drinkify/recipes/Yellow_Bird.jpg",
          "ingredients": [
              {
                  "_id": "654957fc8609e9d50ebca80c",
                  "title": "White Rum",
                  "measure": "3 cl",
                  "ingredientId": "64f1d5cf69d8333cf130fc52"
              },
              {
                  "_id": "654957fc8609e9d50ebca80d",
                  "title": "Galliano",
                  "measure": "1.5 cl",
                  "ingredientId": "64aebb7f82d96cc69e0eb4e4"
              },
              {
                  "_id": "654957fc8609e9d50ebca80e",
                  "title": "Triple Sec",
                  "measure": "1.5 cl",
                  "ingredientId": "64aebb7f82d96cc69e0eb4ac"
              },
              {
                  "_id": "654957fc8609e9d50ebca80f",
                  "title": "Lime Juice",
                  "measure": "1.5 cl",
                  "ingredientId": "64aebb7f82d96cc69e0eb4c1"
              }
          ],
          "shortDescription": "A tropical and fruity cocktail with the flavors of rum, Galliano, lime juice, and pineapple juice."
      }
      },
      "AddOwnDrinkRequest": {
        "type": "object",
        "required": [
          "drink",
          "category",
          "description",
          "alcoholic",
          "glass",
          "instructions",
          "ingredients",
          "drinkThumb"
        ],
        "properties": {
          "drink": {
            "type": "string",
            "description": "Тitle of the drink"
          },
          "description": {
            "type": "string",
            "description": "Drink description"
          },
          "alcoholic": {
            "type": "string",
            "description": "Alcoholic / Non alcoholic",
            "enum": ["Alcoholic", "Non alcoholic"]
          },
          "category": {
            "type": "string",
            "enum": [
              "Ordinary Drink",
              "Cocktail",
              "Shake",
              "Other/Unknown",
              "Cocoa",
              "Shot",
              "Coffee / Tea",
              "Homemade Liqueur",
              "Punch / Party Drink",
              "Beer",
              "Soft Drink"
            ],
            "description": "Select drink category"
          },
          "glass": {
            "type": "string",
            "enum": [
              "Highball glass",
              "Cocktail glass",
              "Old-fashioned glass",
              "Whiskey Glass",
              "Collins glass",
              "Pousse cafe glass",
              "Champagne flute",
              "Whiskey sour glass",
              "Cordial glass",
              "Brandy snifter",
              "White wine glass",
              "Nick and Nora Glass",
              "Hurricane glass",
              "Coffee mug",
              "Shot glass",
              "Jar",
              "Irish coffee cup",
              "Punch bowl",
              "Pitcher",
              "Pint glass",
              "Copper Mug",
              "Wine Glass",
              "Beer mug",
              "Margarita / Coupette glass",
              "Beer pilsner",
              "Beer Glass",
              "Parfait glass",
              "Mason jar",
              "Margarita glass",
              "Martini Glass",
              "Balloon Glass",
              "Coupe Glass"
            ],
            "description": "Select drink glass"
          },
          "instructions": {
            "type": "string",
            "description": "Instructions for drink preparation",
            "example": "Shake and strain into a chilled cocktail glass"
          },
          "ingredients": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string",
                  "description": "Unique identifier for the ingredient"
                },
                "measure": {
                  "type": "string",
                  "description": "Drink ingredient's measure"
                }
              }
            },
            "description": "Drink ingredients"
          },
          "drinkThumb": {
            "type": "string",
            "description": "Drink image url",
            "format": "binary"
          }
        }
      },
      "AddOwnDrinkResponse": {
        "type": "object",
        "properties": {
          "drink": {
            "type": "string",
            "description": "Тitle of the drink"
          },
          "drinkAlternate": {
            "type": "string",
            "description": "Alternate name for the drink"
          },
          "category": {
            "type": "string",
            "description": "Category of the drink"
          },
          "alcoholic": {
            "type": "string",
            "description": "Alcoholic / Non alcoholic"
          },
          "glass": {
            "type": "string",
            "description": "Type of glass the drink should be served in"
          },
          "description": {
            "type": "string",
            "description": "Drink description"
          },
          "drinkThumb": {
            "type": "string",
            "description": "Drink image url"
          },
          "ingredients": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string",
                  "description": "Title of the ingredient" 
                },
                "measure": {
                  "type": "string",
                  "description": "Drink ingredient's measure" 
                },
                "ingredientId": {
                  "type": "string",
                  "description": "Unique identifier for the ingredient"
                },
                "_id": {
                  "type": "string",
                  "description": "Unique identifier for the ingredient in the drink"
                }
              }
            },
            "description": "List of ingredients used in the drink"
          },
          "owner": {
            "type": "string",
            "description": "Owner of the drink"
          },
          "users": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "User IDs associated with the drink"
            },
            "description": "List of user IDs related to the drink"
          },
          "_id": {
            "type": "string",
            "description": "Unique identifier for the new drink"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "description": "Date and time when the drink was created"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time",
            "description": "Date and time when the drink information was last updated"
          }
        },
        "example": {
          "drink": "CovidKiller v5",
          "drinkAlternate": "Sorry, not specified",
          "category": "Soft Drink",
          "alcoholic": "Alcoholic",
          "glass": "Beer Glass",
          "description": "For good kill covid v5",
          "drinkThumb": "https://res.cloudinary.com/dzvvgvwgt/image/upload/v1698700062/drink/shutterstock.jpg.jpg",
          "ingredients": [
              {
                  "title": "Tequila1",
                  "measure": "2 cl",
                  "ingredientId": "64aebb7f82d96cc69e0eb4b8",
                  "_id": "6546a9e5be2bad087d921b28"
              },
              {
                  "title": "Beer",
                  "measure": "2 cl ",
                  "ingredientId": "64f1d5c169d8333cf130fb4a",
                  "_id": "6546a9e5be2bad087d921b29"
              },
              {
                  "title": "Vodka",
                  "measure": "3 cl",
                  "ingredientId": "64aebb7f82d96cc69e0eb4b9",
                  "_id": "6546a9e5be2bad087d921b2a"
              }
          ],
          "owner": "654567fe985e7dfc0b25c2b8",
          "users": [],
          "_id": "6546a9e5be2bad087d921b27",
          "createdAt": "2023-11-04T20:30:29.954Z",
          "updatedAt": "2023-11-04T20:30:29.954Z"
      }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
